### ISSUE TITLE
Permintaan Rework

### ISSUE THREAD

**Issue by radinals** [Rifkisyah/Alpemdas#2]
* Tolong di Rework, bisa ada cara lebih baik untuk menggunakan prosedur.
https://github.com/Rifkisyah/Alpemdas/blob/8d4435dce708aee47435795f035f7893cea1b1d2/Tugas_Praktikum%20%238/%235%20kopi.cpp

**Comment by Rifkisyah** [comment]
baik, maaf sebelumnya saya kurang fokus
